# Generated by Django 5.2 on 2025-04-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaQuadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
                ('reservado', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agenda_quadra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgendaUsuario',
            fields=[
                ('id_agenda', models.AutoField(primary_key=True, serialize=False)),
                ('compromisso', models.CharField(blank=True, max_length=200, null=True)),
                ('data_hora_inicio', models.DateField(blank=True, null=True)),
                ('data_hora_fim', models.DateField(blank=True, null=True)),
                ('data_insert', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agenda_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocaisAtuacao',
            fields=[
                ('id_locais_atuacao', models.AutoField(primary_key=True, serialize=False)),
                ('valor_hora', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dias_disponiveis', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('data_insert', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'locais_atuacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('acao', models.CharField(blank=True, max_length=10, null=True)),
                ('page', models.CharField(blank=True, max_length=20, null=True)),
                ('data_insert', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('data_insert', models.DateTimeField(blank=True, null=True)),
                ('senha', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'pessoa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropietarioQuadra',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=20)),
                ('cnpj', models.CharField(max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('data_insert', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'propietario_quadra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=500)),
                ('bairro', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('preco_hora', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ativo', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'quadra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioPago',
            fields=[
                ('id_usuario_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=120, null=True)),
                ('cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('data_insert', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario_pago',
                'managed': False,
            },
        ),
    ]
