services:
  web:
    build: .
    container_name: django_app
    command: gunicorn pia_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles  # caminho correto onde o Django coloca os arquivos
    ports:
      - "8001:8000"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/staticfiles  # onde o NGINX procura os arquivos estáticos
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    restart: always

volumes:
  static_volume:
